# Generated by Django 4.1.2 on 2022-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0002_livros_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
