# Generated by Django 4.1.2 on 2022-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0003_alter_livros_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images'),
        ),
    ]
